### ISSUE TITLE
Support more IDEA editions and installation methods

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/gnome-intellij-idea-search-provider#2]
Currently this extension only supports IDEA Ultimate installed via `snap`.

It should support Community, and Jetbrains Toolbox.

**Comment by lunaryorn** [comment]
Added support for flatpak and Arch AUR packages of IDEA Ultimate

**Comment by OlegKrikun** [comment]
Please also include support for standalone version.
Probably via extension settings or using environment variable =)

**Comment by lunaryorn** [comment]
Please do open a pull request to add this variant.
